package org.omg.IOP;


/**
* org/omg/IOP/TransactionService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /scratch/HUDSON/workspace/9-2-build-linux-amd64-phase2/jdk9/6725/corba/src/java.corba/share/classes/org/omg/PortableInterceptor/IOP.idl
* Thursday, August 3, 2017 3:57:52 AM UTC
*/

public interface TransactionService
{

  /**
       * Identifies a CDR encapsulation of the 
       * <code>CosTSInteroperation.PropogationContext</code> defined in 
       * <i>CORBAservices: Common Object Services Specifications.</i>
       */
  public static final int value = (int)(0L);
}
