package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/NON_EXISTENT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /scratch/HUDSON/workspace/9-2-build-linux-amd64-phase2/jdk9/6725/corba/src/java.corba/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Thursday, August 3, 2017 3:57:53 AM UTC
*/

public interface NON_EXISTENT
{

  /** Object adapter state indicating that the adapter has been destroyed.
     */
  public static final short value = (short)(4);
}
