package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/ServerManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/8-2-build-linux-i586/jdk8u152/9280.nc/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Wednesday, June 21, 2017 1:30:49 AM PDT
*/

public interface ServerManager extends ServerManagerOperations, com.sun.corba.se.spi.activation.Activator, com.sun.corba.se.spi.activation.Locator
{
} // interface ServerManager
